steps:
  - id: install-npm
    name: node:12-slim
    entrypoint: 'npm'
    args:
      - ci

  - id: angular-lint
    name: asia.gcr.io/pyrovers-site/node-chrome
    entrypoint: 'npm'
    args: ['run', 'lint']
    waitFor:
      - install-npm

  - id: angular-test
    name: asia.gcr.io/pyrovers-site/node-chrome
    entrypoint: 'npm'
    args: ['run', 'test']
    waitFor:
      - angular-lint

  - id: angular-build
    name: node:12.13-slim
    entrypoint: 'npm'
    args: ['run', 'build']
    waitFor:
      - angular-unit-test
