steps:
  - id: install-npm
    name: node:16-slim
    entrypoint: "npm"
    args:
      - ci
    dir: angular

  - id: angular-lint
    name: node:16-slim
    entrypoint: "npm"
    args: ["run", "lint"]
    dir: angular
    waitFor:
      - install-npm

  - id: angular-test
    name: node:16-slim
    entrypoint: "npm"
    args: ["run", "test"]
    dir: angular
    waitFor:
      - angular-lint

  - id: angular-build
    name: node:16-slim
    entrypoint: "npm"
    args: ["run", "build"]
    dir: angular
    waitFor:
      - angular-unit-test
